# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apophis_AppJam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apophis_AppJam
  pod 'Kingfisher', '~> 5.0' 
  pod 'SwiftyJSON','~>4.0'  
  pod 'GIFImageView' 
  pod 'Alamofire', '~> 5.1' 
  pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
  pod 'KakaoSDKAuth'  # 카카오 로그인
  pod 'KakaoSDKUser'  # 카카오 사용자 관리
  pod 'GoogleSignIn' # 구글 로그인

end
