# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Apophis_AppJam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Apophis_AppJam
  pod 'Kingfisher', '~> 5.0' 
  pod 'SwiftyJSON','~>4.0'  
  pod 'GIFImageView' 
  pod 'Alamofire', '~> 5.1' 




end
